const ITEMS = [
  {
    name: 'ハンバーガー用マシン',
    type: '能力',
    income: 50,
    interests: null,
    price: 15000,
    maxNumPossession: 500,
    description: 'クリックするごとに 50 円を取得します。',
    src: 'flip-machine.jpg',
  },
  {
    name: 'レモネードスタンド',
    type: '固定資産',
    income: 500,
    interests: null,
    price: 30000,
    maxNumPossession: 1000,
    description: '毎秒 500 円を取得します。',
    src: 'lemonade-stand.jpg',
  },
  {
    name: 'アイスクリームトラック',
    type: '固定資産',
    income: 1200,
    interests: null,
    price: 60000,
    maxNumPossession: 500,
    description: '毎秒 1200 円を取得します。',
    src: 'icecream-trailer.jpg',
  },
  {
    name: '債券',
    type: '投資',
    income: null,
    interests: 0.01,
    price: 100000,
    maxNumPossession: 100,
    description: '累計購入額の 1% 円を毎秒取得します。',
    src: 'stock.jpg',
  },
  {
    name: '株式',
    type: '投資',
    income: null,
    interests: 0.02,
    price: 200000,
    maxNumPossession: 100,
    description: '累計購入額の 2% 円を毎秒取得しますが、購入する度に10%購入額が増加します。',
    src: 'stock.jpg',
  },
  {
    name: '家',
    type: '固定資産',
    income: 32000,
    interests: null,
    price: 10000000,
    maxNumPossession: 100,
    description: '毎秒 32,000 円を取得します。',
    src: 'house.jpg',
  },
  {
    name: '都会の家',
    type: '固定資産',
    income: 64000,
    interests: null,
    price: 20000000,
    maxNumPossession: 100,
    description: '毎秒 70,000円 を取得します。',
    src: 'urban-house.jpg',
  },
  {
    name: 'マンション',
    type: '固定資産',
    income: null,
    interests: 500000,
    price: 250000000,
    maxNumPossession: 20,
    description: '毎秒 500,000 円を取得します',
    src: 'mansion.jpg',
  },
  {
    name: '産業スペース',
    type: '固定資産',
    income: 2200000,
    interests: null,
    price: 1000000000,
    maxNumPossession: 10,
    description: '毎秒 2,200,000 円を取得します。',
    src: 'industrial-space.jpg',
  },
  {
    name: '高層ホテル',
    type: '固定資産',
    income: 25000000,
    interests: null,
    price: 10000000000,
    maxNumPossession: 5,
    description: '毎秒 25,000,000 円を取得します。',
    src: 'hotel.jpg',
  },
  {
    name: '新幹線',
    type: '固定資産',
    income: 30000000000,
    interests: null,
    price: 1000000000000,
    maxNumPossession: 1,
    description: '毎秒 25,000,000 円を取得します。',
    src: 'shinkansen.png',
  },

];
export default ITEMS;
